In [1]:
import numpy

In [6]:
a = numpy.zeros(10)
a[4] = 1
print (a[:])

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [8]:
b = numpy.arange(10,50)
print (b)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [11]:
c = numpy.flipud(b)
print (b)
print (c)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [13]:
d = numpy.arange(9).reshape(3,3)
print(d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [16]:
e = numpy.array([1,2,0,0,4,0])
numpy.nonzero(e)

(array([0, 1, 4], dtype=int64),)

In [41]:
f = numpy.array(numpy.random.rand(30),dtype=numpy.float64)
mean=f.sum()/30.0
print (mean)


0.5025665818468352


In [45]:
g=numpy.zeros((10,10))
g[0,:]=1;
g[9,:]=1
g[:,0]=1
g[:,9]=1
print (g)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [54]:
h = numpy.zeros((8,8),dtype=int)
h[1::2,::2] = 1
h[::2,1::2] = 1
print(h)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [62]:
I1 = numpy.array([(0,1,0,1,0,1,0,1),(1,0,1,0,1,0,1,0)])
numpy.tile(I1,(4,1))


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [68]:
J=numpy.arange(11)
index = numpy.where((J>2) & (J<9))
J[index] *=-1
print(J)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


In [70]:
K = numpy.random.rand(10)
K=numpy.sort(K)
print(K)

[0.27123439 0.27766114 0.29316209 0.37883554 0.44538518 0.61192538
 0.64071612 0.7409866  0.82754137 0.82947163]


In [73]:
A = numpy.random.randint(0,2,5)
B = numpy.random.randint(0,2,5)
equal = numpy.allclose(A,B)
print(equal)

False


In [76]:
Z = numpy.arange(10, dtype=numpy.int32)
print(Z.dtype)
Z =numpy.float32(Z)
print(Z.dtype)

int32
float32


In [77]:
A = numpy.arange(9).reshape(3,3)
B = A + 1
C = numpy.dot(A,B)
D = numpy.diag(C)
print(C)
print(D)

[[ 18  21  24]
 [ 54  66  78]
 [ 90 111 132]]
[ 18  66 132]
